### ISSUE TITLE
Add vendor

### ISSUE THREAD

**Issue by egorsmkv** [ahmetalpbalkan/go-httpbin#4]
I think you should add vendoring. What do you think about [govendor](https://github.com/kardianos/govendor)?

**Comment by egorsmkv** [comment]
And why in tests files imports github.com/ahmetalpbalkan/go-httpbin ?
I can't run tests because of this.

**Comment by ahmetalpbalkan** [comment]
We're a library, it's not very recommended for libraries to vendor libs. Plus I think we only have test dependencies (so that's not really a really dependency?) so we don't really need to vendor. 

Tests are in another package so that we only test the exported methods also the ExampleXxx method shows the usage with package name included. This is a common practice, even used in stdlib.

**Comment by egorsmkv** [comment]
Understood.
